-- =========================
-- SEQUENCES
-- =========================

CREATE SEQUENCE seq_departments
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE SEQUENCE seq_jobs
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE SEQUENCE seq_employees
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE SEQUENCE seq_payroll
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE SEQUENCE seq_leaves
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE SEQUENCE seq_attendance
START WITH 1
INCREMENT BY 1
NOCYCLE;